### ISSUE TITLE
Make installable via Scoop

### ISSUE THREAD

**Issue by JanPokorny** [shilangyu/scoop-search#10]
Installing this using Scoop seems like the most logical choice. (I can pick it up if you don't want to create a manifest yourself. I'm just creating the issue to know why this is not in Scoop, since it really seems like a weird oversight.)

**Comment by shilangyu** [comment]
I did consider this, but it felt 'weird' submitting it myself. Feel free to do it and let me know if you need help with the manifest, I have prior experience with those.

**Comment by JanPokorny** [comment]
I actually think that _not_ submitting it is weirder, and it led me to believe there is no such tool available (since I tried `scoop search search` and it didn't produce anything useful). I have submitted https://github.com/ScoopInstaller/Main/pull/1703

**Comment by shilangyu** [comment]
For now I have added the manifest to the repo so it can be installed with scoop by pointing to it: https://github.com/shilangyu/scoop-search/commit/78108c69a2bcae3953b0a586ffaec7daaeeab3be

Will remove it once it is officially on scoop

**Comment by shilangyu** [comment]
Thank you for your help, I have updated the README to point to the official scoop manifest :)
