### ISSUE TITLE
Use %SCOOP% variable, if defined

### ISSUE THREAD

**Issue by rasa** [shilangyu/scoop-search#11]
https://github.com/shilangyu/scoop-search/blob/85153afb9d982f44a2c38ac5f2ca2942fe92d029/main.go#L34

If `%SCOOP%` is defined, the buckets dir will be found in `%SCOOP%\buckets`. See https://github.com/lukesampson/scoop/wiki/Quick-Start#installing-scoop-to-custom-directory

**Comment by shilangyu** [comment]
Support added, feel free to reopen if there are issues with it.
