### ISSUE TITLE
can not run

### ISSUE THREAD

**Issue by xianzheTM** [shilangyu/scoop-search#19]
```
$> scoop search zoc
panic: runtime error: index out of range [1] with length 1

goroutine 7 [running]:
main.matchingManifests(0xc0001800f0, 0x28, 0xc000010098, 0x3, 0x0, 0x0, 0x0)
        /home/runner/work/scoop-search/scoop-search/main.go:133 +0x106b
main.main.func1(0xc00000c420, 0x1c, 0xc000010098, 0x3, 0x0, 0xc000052280, 0xc000010170, 0x862f00, 0xc000122000)
        /home/runner/work/scoop-search/scoop-search/main.go:70 +0x185
created by main.main
        /home/runner/work/scoop-search/scoop-search/main.go:63 +0x253
```
version:1.1.0
OS:win11

**Comment by shilangyu** [comment]
Looks like one of the manifests has an incorrect format. Could you show you your list of buckets?

**Comment by xianzheTM** [comment]
> Looks like one of the manifests has an incorrect format. Could you show you your list of buckets?

That would be too bad.  Because I'm using an aggregated bucket that merges a lot of buckets.
https://github.com/kkzzhizhou/scoop-apps

**Comment by shilangyu** [comment]
Thanks, will check them. Its the second time that this happened with this user's manifests: https://github.com/shilangyu/scoop-search/issues/12

**Comment by shilangyu** [comment]
I've decided to silently support this. Though these are incorrect manifest and it would be better to fix them upstream.
