### ISSUE TITLE
scoop-search 1.1.0 reported as dangerous by CrowdStrike Falcon

### ISSUE THREAD

**Issue by vvuk** [shilangyu/scoop-search#20]
the 1.1.0 executable gets reported as dangerous by Falcon AV; I don't have any additional information, as it's our corporate AV solution and I don't have much visibility into it.  But other AV solutions may be triggering on the same thing, which could lead to scoop-search.exe being deleted transparently or quarantined which would look like it just doesn't work.

**Comment by vvuk** [comment]
Looks like a few overzealous AVs are flagging this: https://www.virustotal.com/gui/file/6a4a965371bc07315f784e56adce8965f88f6889aef761bf11e5f15d2e281db7

**Comment by shilangyu** [comment]
Is that known to be the case with Golang binaries? Nothing special is being done here, binaries are built straight from the GitHub source code without any additions

**Comment by shilangyu** [comment]
Released a new version built with the newest stable Golang compiler. Maybe some it will help.

**Comment by shilangyu** [comment]
Closing as I don't think I am able to do anything here. Dependencies are kept up to date. Feel free to reopen if you feel this should be properly taken care of.
