### ISSUE TITLE
Don't work if SCOOP not a variable in your environment

### ISSUE THREAD

**Issue by MainEditor** [shilangyu/scoop-search#28]
Solution is manually create SCOOP var for current user. I'm came to this by read this function in main.go. That happens because Scoop adds himself to PATH insted of making it's own var. I'm don't think you need to change code because it's already work fine but add the section about this to README.md

```
func scoopHome() (res string) {
    if value, ok := os.LookupEnv("SCOOP"); ok {
        res = value
    } else {
        var err error
        res, err = os.UserHomeDir()
        checkWith(err, "Could not determine home dir")

        res += "\\scoop"
    }

    return
}
```

Sorry for bad screenshot.

![изображение](https://user-images.githubusercontent.com/98752769/209928891-3c71bcf4-b513-4044-ae2d-4c5a259f7c0e.png)

**Comment by shilangyu** [comment]
> That happens because Scoop adds himself to PATH insted of making it's own var

Could you clarify what you mean here? By design (mirroring what scoop itself does) the `SCOOP` env var allows to override the home directory of scoop (where scoop will download packages). But if the variable is not present, it will default to `~/scoop`

**Comment by MainEditor** [comment]
Oh I mean "don't" sorry. `SCOOP` var is not added by defult if scoop installed on other drive(At least when I'm installed it on my PC). I'm added it myself to make `scoop-search` work

**Comment by shilangyu** [comment]
So you are saying `scoop search` worked, but `scoop-search` did not, and the fix was to add the env var? I am a little bit confused, as `scoop-search` mostly mimics `scoop search` behavior of finding the root path.
