### ISSUE TITLE
Getting "Scoop folder does not exist - open \buckets: The system cannot find the file specified."

### ISSUE THREAD

**Issue by svk-works** [shilangyu/scoop-search#31]
![image](https://user-images.githubusercontent.com/59787884/214583815-007dafec-3f2e-4638-b0bb-ccaf66684ba2.png)

**Comment by eidswe** [comment]
Temporary solution:scoop reset scoop-search@1.2.0

**Comment by shilangyu** [comment]
Released version `1.3.1`. Please let me know if this does not fix the issue.

**Comment by eidswe** [comment]
Yes, the issue has been fixed.

**Comment by svk-works** [comment]
> Released version `1.3.1`. Please let me know if this does not fix the issue.

Yup, it's fixed now. Thank you :)
