### ISSUE TITLE
slow on first search

### ISSUE THREAD

**Issue by c-ortbauer** [shilangyu/scoop-search#33]
Hi,

the search works great and is very fast for me, except on the first search, that one always takes around 10s.
Subsequent searches give an immediate result. Only after around an hour without any searches there is one other very slow search.

Does anyone know the reason for this behavior? Is there some caching or indexing going on?

Thanks in advance!

**Comment by shilangyu** [comment]
Sounds like some NTFS indexing. I am not very versed with NTFS, but will see what I can do here.

**Comment by akirco** [comment]
> Hi,
> 
> the search works great and is very fast for me, except on the first search, that one always takes around 10s. Subsequent searches give an immediate result. Only after around an hour without any searches there is one other very slow search.
> 
> Does anyone know the reason for this behavior? Is there some caching or indexing going on?
> 
> Thanks in advance!

Since this problem, i write a toy https://github.com/akirco/shell-scripts/blob/master/scoop-search/scoop-search.ps1

**Comment by shilangyu** [comment]
Closing because there is nothing I can do here. Reading files is done using syscalls provided by windows. If anyone is aware of a way to bypass this slow initial search I am open for suggestions.
