### ISSUE TITLE
When the powershell window is closed, the hook will become invalid. 

### ISSUE THREAD

**Issue by ihuanx** [shilangyu/scoop-search#35]
When the powershell window is closed, the hook will become invalid. You need to reset the hook the next time you start powershell. This is too troublesome.

**Comment by shilangyu** [comment]
I see you closed the issue, did you resolve it?

**Comment by ihuanx** [comment]
```echo "Invoke-Expression (&scoop-search --hook)" > "C:\Windows\System32\WindowsPowerShell\v1.0\profile.ps1"```

My English is not good. So I didn’t understand the readme at the beginning. I solved it through this method now.

thanks ~
