### ISSUE TITLE
Cannot parse "bin" attribute in a manifest. This should not happen. Please open an issue about it with steps to reproduce

### ISSUE THREAD

**Issue by berial** [shilangyu/scoop-search#36]
```
 $ scoop-search google
```

2023/12/11 10:43:39 Cannot parse "bin" attribute in a manifest. This should not happen. Please open an issue about it with steps to reproduce

**Comment by shilangyu** [comment]
Could you please attack a list of buckets you have installed? Thanks

**Comment by berial** [comment]
```
$ scoop bucket list
```

|Name|Source|Updated|Manifests|
|---- |  ------       |                            -------         |    ---------|
|apps |https://github.com/kkzzhizhou/scoop-apps| 2023/12/10 12:43:44   |  12946|
|extras |https://github.com/ScoopInstaller/Extras| 2023/12/11 08:31:53   |   1889|
|java   |https://github.com/ScoopInstaller/Java   |2023/12/10 20:24:58   |    267|
|main   |https://github.com/ScoopInstaller/Main   |2023/12/11 08:32:37  |    1266|
|okibcn |https://github.com/okibcn/ScoopMaster   | 2023/12/11 10:26:33   |  45622|

**Comment by hawcgn** [comment]
I also encountered the same problem. Before it was normal, suddenly it reported this error!

`bucket list:`

![image](https://github.com/shilangyu/scoop-search/assets/150403800/c2e851cc-f6c3-4b36-ae35-5890376f2ba5)

**Comment by shilangyu** [comment]
Sorry for the delay, I finally have some time to look at it today. I suspect either a malformed manifest (which should be preferably fixed downstream) or scoop changed how the manifest looks like.

**Comment by hawcgn** [comment]
How should I solve this problem?
What steps should I take to solve this problem?
I have no clue!

**Comment by shilangyu** [comment]
Unfortunately I don't produce any diagnostics so the only way to debug this is to run a locally compiled version of scoop-search that will print out the path to the malformed manifest.

This error appears because it tries to parse a manifest file but fails to do so because it expects a field that is not there. I will take a look at it today in the evening. I will also change the error message to be more informative.

**Comment by shilangyu** [comment]
The problem is in the ScoopMaster repo. They have some malformed manifest there. Adding this repo as a bucket takes forever, so I will leave it overnight and check tomorrow which is the offending manifest.

**Comment by shilangyu** [comment]
Well actually, screw it. I cannot fight against all incorrectly written manifests. I released [v1.3.2](https://github.com/shilangyu/scoop-search/releases/tag/v1.3.2) that silently ignores incorrect manifests. It should work for you now.

**Comment by hawcgn** [comment]
yeah, it worked. Thank you very much!
