### ISSUE TITLE
Release 1.3.2 identified as suspect

### ISSUE THREAD

**Issue by captainkirkoff** [shilangyu/scoop-search#37]
Ms Defender finds Trojan:Win32/Wacatac.H!ml in the executable and removes it.

![image](https://github.com/shilangyu/scoop-search/assets/6802846/a3913aa3-89dd-4549-965a-ab8d0d26c54d)

**Comment by shilangyu** [comment]
Closing with the same intention as in #20. I don't see how I can do anything here. Binaries are built straight from source by github actions (everything is public). Dependencies are kept up to date. Feel free to reopen if you see some actions that can be taken here.
