### ISSUE TITLE
Gdata reports virus in scoop-search.exe 1.3.2

### ISSUE THREAD

**Issue by ExpPhysU** [shilangyu/scoop-search#39]
Gdata blocks scoop-search.exe version 1.3.2  because of

Trojan.GenericKD.71092350

Search is not working.

Thanks

**Comment by ExpPhysU** [comment]
Comment Version 1.3.1 is not affected

**Comment by shilangyu** [comment]
Please post the detailed antivirus report. See also https://github.com/shilangyu/scoop-search/issues/37 for information that most likely I won't be able to help here.

**Comment by shilangyu** [comment]
I pushed a new version with updated github actions. That shouldn't change anything. There is nothing more I can do. [See here](https://github.com/shilangyu/scoop-search/issues/37#issuecomment-1872177871).
