### ISSUE TITLE
Does not work with scoop installed on other path

### ISSUE THREAD

**Issue by kewubenduben** [shilangyu/scoop-search#55]
My scoop is installed on a custom path which shows this error when using `scoop-search`.

```
PS C:\Applications\Scoop\apps\scoop-search> scoop search mono
Could not open the buckets directory: C:\Users\username/scoop/buckets.
```

**Comment by shilangyu** [comment]
How do you configure your custom path? Do you set the `SCOOP` env var or you set `root_path` in your scoop config?

**Comment by kewubenduben** [comment]
I've fixed it already by setting `root_path` manually.

My scoop build is a recovered installation from old backup and recofingured by doing `scoop reset *`. 

Anyways, consider this as done.

Thanks
