### ISSUE TITLE
Push Binary

### ISSUE THREAD

**Issue by skanda890** [shilangyu/scoop-search#61]
Unfortunately, I do not understand and you are not telling me why this is being done. Feel free to open an issue instead, I will be happy to help.

_Originally posted by @shilangyu in https://github.com/shilangyu/scoop-search/issues/60#issuecomment-2214253497_

**Comment by skanda890** [comment]
Re-open #60

**Comment by shilangyu** [comment]
@skanda890 please tell me why this is needed. Releases of scoop-search include binaries. https://github.com/shilangyu/scoop-search/releases/tag/v1.5.0

**Comment by skanda890** [comment]
First, when I wanted to merge branches I went to skanda890/scoop-search found two branches named  , merged them into the default branch, and created #57 then you closed it saying that the base branch has been updated, etc, and I created #60 and since Debug Logging was already fixed we remain with only Pushing Binary, and that is why I wanted to merge #60.

**Comment by skanda890** [comment]
I am creating one more pull request, as you saw my explanation please allow to merge that pull request.

**Comment by shilangyu** [comment]
But _why_ is the binary being pushed?

**Comment by shilangyu** [comment]
Closing due to no direct response to my question. Feel free to comment with an answer and I will be happy to help.

**Comment by skanda890** [comment]
In the commit shown above, we see that you have called it Push
