### ISSUE TITLE
It't very  good  ,  if   rewrite  with rust  whether  if   better    

### ISSUE THREAD

**Issue by Super1Windcloud** [shilangyu/scoop-search#68]
## Logs

The offending command causing the error with the `$env:SCOOP_SEARCH_VERBOSE=1` env var set:

<details>
  <summary>Output</summary>
  
  ```txt
  ```
</details>

**Comment by shilangyu** [comment]
I wrote it in zig for fun. I don't think rewriting it in rust will have many benefits. Feel free to reopen if you meant something else
